baseURL: 'https://goofy-nightingale-b79575.netlify.app/'
languageCode: 'en-us'
title: 'On Horn Playing'
# theme: hugo-theme-library

params:
  mainSections: ['books']

module:
  imports:
    path: "github.com/juliuspr/hugo-theme-library"
    mounts:
      source: "layouts"
      target: "layouts"
