baseURL: "https://goofy-nightingale-b79575.netlify.app/"
languageCode: "en-us"
title: "On Horn Playing"

params:
  mainSections: ["books"]

module:
  imports:
    - path: "github.com/juliuspr/hugo-theme-library"

  # - path: 'github.com/juliuspr/horn-playing-resources'
  #   ignoreConfig: true
  #   mounts:
  #     source: "content"
  #     target: "content/playing"
